# Generated by Django 5.0.1 on 2024-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('A', 'Public'), ('B', 'Unlisted'), ('C', 'Private')], default='C', max_length=1),
        ),
    ]
