# Generated by Django 5.0.1 on 2024-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_coursepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='title',
            field=models.TextField(default='Page '),
        ),
    ]
