# Generated by Django 5.0.1 on 2024-05-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_coursepage_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='has_answer',
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='answer_type',
            field=models.CharField(choices=[('N', None), ('T', 'Text'), ('C', 'Singular Choice'), ('M', 'Multiple Choice'), ('F', 'File Upload')], default='N', max_length=1),
        ),
    ]
