# Generated by Django 5.0.1 on 2024-05-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_coursepage_has_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageanswertext',
            old_name='text',
            new_name='text_answer',
        ),
    ]
