# Generated by Django 5.0.1 on 2024-05-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_text_pageanswertext_text_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageanswertext',
            old_name='text_answer',
            new_name='text_preset',
        ),
    ]
