# Generated by Django 5.0.1 on 2024-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_text_answer_pageanswertext_text_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageanswertext',
            name='text_preset',
        ),
        migrations.AddField(
            model_name='pageanswertext',
            name='is_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pageanswertext',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pageanswertext',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
