# Generated by Django 5.0.1 on 2024-05-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_pageanswertext_text_preset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageanswertext',
            name='user',
        ),
    ]
