# Generated by Django 5.0.1 on 2024-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_coursepage_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanswertext',
            name='choices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='answer_type',
            field=models.CharField(choices=[('N', None), ('T', 'Text'), ('S', 'Singular Choice'), ('M', 'Multiple Choice'), ('F', 'File Upload')], default='N', max_length=1),
        ),
    ]
