# Generated by Django 5.0.1 on 2024-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_pageanswertext_choices_alter_coursepage_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageanswertext',
            name='choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
