# Generated by Django 5.0.1 on 2024-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_pageanswertext_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageanswertext',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
