# Generated by Django 5.0.1 on 2024-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_pageanswertext_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanswertext',
            name='correct_choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
