# Generated by Django 5.0.1 on 2024-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_pageanswertext_correct_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageanswertext',
            name='correct_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
