# Generated by Django 5.0.1 on 2024-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_studentanswertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswertext',
            name='answer_type',
            field=models.CharField(choices=[('N', None), ('T', 'Text'), ('S', 'Singular Choice'), ('M', 'Multiple Choice'), ('F', 'File Upload')], default='N', max_length=1),
        ),
    ]
