# Generated by Django 5.0.1 on 2024-05-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_usergroups_groupenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperms',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupenrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usergroups'),
        ),
    ]
