# Generated by Django 5.0.1 on 2024-05-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_pageanswertext_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageanswertext',
            name='student',
        ),
    ]
