# Generated by Django 5.0.1 on 2024-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_pageanswertext_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
