# Generated by Django 5.0.1 on 2024-06-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_coursepage_is_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='time',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AddField(
            model_name='pageanswertext',
            name='correct_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageanswertext',
            name='incorrect_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CurrentPageControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.coursepage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usergroups')),
            ],
        ),
    ]
