# Generated by Django 5.0.1 on 2024-06-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_studentanswerfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentPageControl',
        ),
    ]
