# Generated by Django 5.0.1 on 2024-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_groupassignments_deadline_userpfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpfp',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
