# Generated by Django 5.0.1 on 2024-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_userpfp_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpfp',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='backend/media/user_pfps/'),
        ),
    ]
