# Generated by Django 5.0.1 on 2024-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_userpfp_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageanswertext',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
