# Generated by Django 5.0.1 on 2024-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_pageanswertext_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswerfile',
            name='response',
            field=models.FileField(default=None, upload_to='user_responses/'),
        ),
    ]
