# Generated by Django 5.0.1 on 2024-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_studentanswerfile_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswerfile',
            name='response',
            field=models.FileField(blank=True, default=None, null=True, upload_to='user_responses/'),
        ),
    ]
