# Generated by Django 5.0.1 on 2024-06-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_notifications_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
